/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ulbra.gde;

import br.edu.ulbra.gde.view.*;

/**
 *
 * @author Thiago Moura
 */
public class FrameMain extends javax.swing.JFrame {

    private PessoaFisicaFrame pFisica = PessoaFisicaFrame.getInstance();
    private PessoaJuridicaFrame pJuridica = PessoaJuridicaFrame.getInstance();
    private NotaFiscalFrame notaFiscalFrame = NotaFiscalFrame.getInstance();

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        desktopMain.add(pFisica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        desktopMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPessoa = new javax.swing.JMenu();
        mitPessoaFisica = new javax.swing.JMenuItem();
        mitPessoaJuridica = new javax.swing.JMenuItem();
        menuNotaFiscal = new javax.swing.JMenu();
        mitNotaFiscal = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopMainLayout = new javax.swing.GroupLayout(desktopMain);
        desktopMain.setLayout(desktopMainLayout);
        desktopMainLayout.setHorizontalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        desktopMainLayout.setVerticalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(desktopMain);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        menuPessoa.setText("Pessoa");

        mitPessoaFisica.setText("Pessoa Fisica");
        mitPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPessoaFisicaActionPerformed(evt);
            }
        });
        menuPessoa.add(mitPessoaFisica);

        mitPessoaJuridica.setText("Pessoa Juridica");
        mitPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPessoaJuridicaActionPerformed(evt);
            }
        });
        menuPessoa.add(mitPessoaJuridica);

        jMenuBar1.add(menuPessoa);

        menuNotaFiscal.setText("Nota Fiscal");

        mitNotaFiscal.setText("Nota Fiscal");
        mitNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNotaFiscalActionPerformed(evt);
            }
        });
        menuNotaFiscal.add(mitNotaFiscal);

        jMenuBar1.add(menuNotaFiscal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPessoaFisicaActionPerformed
        if (pFisica.isClosed()) {
            pFisica = PessoaFisicaFrame.AbrirNovo(desktopMain);
        } else {
            if (pFisica.isIcon()) {
                pFisica.maximizar();
            } else {
                pFisica.selecionar();
            }
        }
    }//GEN-LAST:event_mitPessoaFisicaActionPerformed

    private void mitPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPessoaJuridicaActionPerformed
        if (pJuridica.isClosed()) {
            pJuridica = PessoaJuridicaFrame.AbrirNovo(desktopMain);
        } else {
            if (pJuridica.isIcon()) {
                pJuridica.maximizar();
            } else {
                pJuridica.selecionar();
            }
        }
    }//GEN-LAST:event_mitPessoaJuridicaActionPerformed

    private void mitNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNotaFiscalActionPerformed
        if (notaFiscalFrame.isClosed()) {
            notaFiscalFrame = NotaFiscalFrame.AbrirNovo(desktopMain);
        } else {
            if (notaFiscalFrame.isIcon()) {
                notaFiscalFrame.maximizar();
            } else {
                notaFiscalFrame.selecionar();
            }
        }
     }//GEN-LAST:event_mitNotaFiscalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuNotaFiscal;
    private javax.swing.JMenu menuPessoa;
    private javax.swing.JMenuItem mitNotaFiscal;
    private javax.swing.JMenuItem mitPessoaFisica;
    private javax.swing.JMenuItem mitPessoaJuridica;
    // End of variables declaration//GEN-END:variables

}
